name: proyecto_moviles2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # Otras dependencias
  pdf: ^3.6.0
  printing: ^5.6.0
  path_provider: ^2.0.11
  intl: ^0.20.2
  image_picker: ^1.0.4
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  http: ^1.2.1
  flutter_dotenv: ^5.0.2

  # Para abrir PDFs desde la app
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/usuario.png